-- MySQL Script generated by MySQL Workbench
-- Sat Dec 17 18:27:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SuspirarDoces
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SuspirarDoces` ;

-- -----------------------------------------------------
-- Schema SuspirarDoces
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuspirarDoces` DEFAULT CHARACTER SET utf8mb4 ;
USE `SuspirarDoces` ;

-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `sobrenome` VARCHAR(40) CHARACTER SET 'utf8mb4' NULL,
  `cpf` VARCHAR(11) CHARACTER SET 'utf8mb4' NULL,
  `telefone` VARCHAR(11) CHARACTER SET 'utf8mb4' NOT NULL,
  `cidade` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NULL,
  `dataRemocao` DATETIME NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(35) CHARACTER SET 'utf8mb4' NOT NULL,
  `descricao` VARCHAR(75) CHARACTER SET 'utf8mb4' NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `qtdeOvos` INT NOT NULL,
  `qtdeAcucar` DOUBLE NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NULL,
  `dataRemocao` DATETIME NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Estoques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Estoques` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Estoques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `quantidade` INT NOT NULL,
  `quantidadeMinima` INT NOT NULL,
  `dataUltimaCompra` DATETIME NOT NULL,
  `valorUltimaCompra` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `valorEntrada` DECIMAL(6,2) NOT NULL,
  `valorAPagar` DECIMAL(6,2) NOT NULL,
  `valorTotal` DECIMAL(6,2) NOT NULL,
  `pago` TINYINT NOT NULL DEFAULT 0,
  `dataPedido` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NULL,
  `dataRemocao` DATETIME NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `origemPedido` VARCHAR(30) CHARACTER SET 'utf8mb4' NOT NULL,
  `observacao` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL,
  `isRetirada` TINYINT NOT NULL,
  `localEntrega` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL,
  `dataHoraEntrega` DATETIME NULL,
  `entregue` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `SuspirarDoces`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`ProdutosPedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`ProdutosPedidos` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`ProdutosPedidos` (
  `idProdutosPedidos` INT NOT NULL AUTO_INCREMENT,
  `idProdudo` INT NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idProdutosPedidos`),
  UNIQUE INDEX `idProdutosPedidos_UNIQUE` (`idProdutosPedidos` ASC) VISIBLE,
  INDEX `idProduto_idx` (`idProdudo` ASC) VISIBLE,
  INDEX `idPedido_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `idProduto`
    FOREIGN KEY (`idProdudo`)
    REFERENCES `SuspirarDoces`.`Produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `SuspirarDoces`.`Pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Receitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Receitas` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPedidoReceita` INT NULL,
  `origem` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NULL,
  `dataRemocao` DATETIME NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `idPedidoReceita_idx` (`idPedidoReceita` ASC) VISIBLE,
  CONSTRAINT `idPedidoReceita`
    FOREIGN KEY (`idPedidoReceita`)
    REFERENCES `SuspirarDoces`.`Pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`Despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`Despesas` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`Despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NULL,
  `dataRemocao` DATETIME NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`ResultadoMensal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`ResultadoMensal` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`ResultadoMensal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataInclusao` DATETIME NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`ResultadoTrimestral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`ResultadoTrimestral` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`ResultadoTrimestral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataInclusao` DATETIME NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`ResultadoSemestral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`ResultadoSemestral` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`ResultadoSemestral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataInclusao` DATETIME NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuspirarDoces`.`ResultadoAnual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuspirarDoces`.`ResultadoAnual` ;

CREATE TABLE IF NOT EXISTS `SuspirarDoces`.`ResultadoAnual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataInclusao` DATETIME NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
